inertial_frame_id: world
waypoints:
- heading: 0.0
  max_forward_speed: 0.4
  point:
  - 0.0
  - 0.0
  - -2.0
  use_fixed_heading: false
- heading: 0.0
  max_forward_speed: 0.4
  point:
  - 5.0
  - 0.0
  - -2.0
  use_fixed_heading: false
- heading: 0.0
  max_forward_speed: 0.4
  point:
  - 5.0
  - 5.0
  - -2.0
  use_fixed_heading: false
- heading: 0.0
  max_forward_speed: 0.4
  point:
  - -5.0
  - 5.0
  - -2.0
  use_fixed_heading: false
- heading: 0.0
  max_forward_speed: 0.4
  point:
  - -5.0
  - -5.0
  - -2.0
  use_fixed_heading: false
- heading: 0.0
  max_forward_speed: 0.4
  point:
  - 5.0
  - -5.0
  - -2.0
  use_fixed_heading: false
- heading: 0.0
  max_forward_speed: 0.4
  point:
  - 0.0
  - 0.0
  - -2.0
  use_fixed_heading: false
