inertial_frame_id: world
waypoints:
  -
    point: [-15, 0, -18]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-17, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-20, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-23, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-25, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-27, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
