inertial_frame_id: world
waypoints:
  -
    point: [0, 0, -18]
    max_forward_speed: 0.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-5, 0, -18]
    max_forward_speed: 0.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-9, 0, -18]
    max_forward_speed: 0.5
    heading: 0
    use_fixed_heading: False
  -
    point: [-11, 0, -18]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-15, 0, -18]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-17, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-20, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-23, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  -
    point: [-25, 0, -17]
    max_forward_speed: 0.2
    heading: 0
    use_fixed_heading: False
  