inertial_frame_id: world
waypoints:
  -
    point: [0, 10, -18]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 6, -18]
    max_forward_speed: 1.5
    heading: 0
    use_fixed_heading: False
  -
    point: [3, 6, -18]
    max_forward_speed: 0.5
    heading: 0
    use_fixed_heading: False
  -
    point: [6, 6, -18]
    max_forward_speed: 0.5
    heading: 0
    use_fixed_heading: False
  -
    point: [6, 5, -18]
    max_forward_speed: 0.5
    heading: 0
    use_fixed_heading: False

